feat: pending friend request
OfirMatasas/Notify pull request #93
Opened 2023-07-25 17:17 UTC by LinMoskovitch

## Description: 
what are the changes you implemented?

## Type of change:
- [ ] Bug fix
- [ ] New feature
- [ ] Fix/new infrastructure

## Background context of the changes:
Why do we need those changes?

## The ticket this PR closes:
Put a link to the ticket on Jira we're closing using this pull request.

## Where should the reviewer start?
If the changes are spreading over serveral files, let the reviewer know where to start.

## Scenarios that were tested during this implementation:
List the scenarios you tested for this changes.

## Insert screenshots / video of test results (for all relevant platforms)
If you implemented a new workflow / fixed a bug in a certain workflow, you can provide a proof it's working here.

2023-07-29 06:04 UTC, OfirMatasas requested changes
Awesome work in general!
See my comments.

2023-07-29 06:04 UTC, OfirMatasas commented on Notify/Notify/Notify/ViewModels/PendingFriendRequestsPageViewModel.cs
> +                foreach (FriendRequest friendRequest in pendingFriendRequests)
Space before foreach loop.

2023-07-29 06:04 UTC, OfirMatasas commented on Notify/Notify/Notify/ViewModels/PendingFriendRequestsPageViewModel.cs
> +                userName = Preferences.Get(Constants.PREFERENCES_USERNAME, "");
Use string.Empty instead of "".

2023-07-29 06:04 UTC, OfirMatasas commented on Notify/Notify/Notify/ViewModels/PendingFriendRequestsPageViewModel.cs
> +            r_Logger.LogDebug($"{FriendRequests.Count} Pending friend requests found in preferences");
Space after the curly brackets.

2023-07-29 06:04 UTC, OfirMatasas commented on Notify/Notify/Notify/ViewModels/PendingFriendRequestsPageViewModel.cs
> +            r_Logger.LogDebug($"{FriendRequests.Count} Pending friend requests found in preferences");
What is log should inform us about?

2023-07-29 06:04 UTC, OfirMatasas commented on Notify/Notify/Notify/Views/SubViews/FriendRequestPage.xaml
> +    xmlns:materialDesignControls="clr-namespace:Plugin.MaterialDesignControls;assembly=Plugin.MaterialDesignControls"
Thank god.
I thought I was not changeable.

2023-07-29 06:04 UTC, OfirMatasas commented on Notify/Notify/Notify/Views/SubViews/PendingFriendRequestsPage.xaml
> +
Drop the extra space.

2023-07-29 18:27 UTC, LinMoskovitch commented on Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Users/GetNotFriendUsers.cs
> +            else if (!await ValidationUtils.DoesUsernameExist(username))
I didnt write this endpoint

2023-07-29 18:28 UTC, LinMoskovitch commented on Notify/Notify/Notify/Azure/HttpClient/AzureHttpClient.cs
> +                { "requestDate", DateTime.Now.Date.ToShortDateString() }
No

2023-07-30 04:52 UTC, OfirMatasas commented on Notify/Notify/Notify/Azure/HttpClient/AzureHttpClient.cs
> +                { "requestDate", DateTime.Now.Date.ToShortDateString() }
But we've used the timestamp all over the application.
We have to stay persistence.
Plus, the unix timestamp is the good-practice way to save dates.

2023-07-30 04:53 UTC, OfirMatasas commented on Notify/Notify/Notify/ViewModels/FriendRequestPageViewModel.cs
> +            if (!(friend is null))
I think you can use "is not".

2023-07-30 04:54 UTC, LinMoskovitch commented on Notify/Notify/Notify/ViewModels/FriendRequestPageViewModel.cs
> +            if (!(friend is null))
I tried

2023-07-30 05:02 UTC, OfirMatasas approved these changes
Great job!

2023-07-30 07:38 UTC, merged